"""
analysis/sro.py
===============
Stage 9 — Warren-Cowley short-range order (SRO) parameters.

Interface (called by run_pipeline.py)
--------------------------------------
    process(sim_base: Path, txt_dir: Path,
            plot_dir: Path, comp_label: str) -> None

Physics
-------
SRO is read from MD_T_<T>K.txt (written by the LAMMPS fix ave/time block).

Warren-Cowley parameter (Cowley 1950):
    α_ij = 1 − P_ij / x_j

where:
    P_ij = conditional probability of finding j as neighbour of i
         = (avg coord_ij) / z_i
    z_i  = total coordination of i = Σ_j avg coord_ij
    x_j  = bulk mole fraction of j

Interpretation:
    α_ij = 0   : random mixing
    α_ij > 0   : i−j pairs depleted  (like-atom clustering)
    α_ij < 0   : i−j pairs enriched  (chemical ordering)

SRO cutoff r_sro used in the LAMMPS compute is the BCC 1NN/2NN midpoint
(see config.compute_r_sro), which safely captures the first shell for all
elements including Zr (r_1NN = 3.10 Å).

Output
------
    results/<comp_id>/txt/sro_<T>K.txt
    results/<comp_id>/plots/sro_heatmap_<comp_label>.png
"""

from __future__ import annotations

import argparse
import glob
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent))

# All possible pairs for 6 elements (36 total, including self-pairs)
ELEMENTS_ALL = ["W", "Mo", "Nb", "Zr", "Ti", "Ta"]
ALL_PAIRS = [(a, b) for a in ELEMENTS_ALL for b in ELEMENTS_ALL]

COLORS_CYCLE = [
    "#1f77b4","#ff7f0e","#2ca02c","#d62728","#9467bd",
    "#8c564b","#e377c2","#7f7f7f","#bcbd22","#17becf",
    "#aec7e8","#ffbb78","#98df8a","#ff9896","#c5b0d5",
    "#c49c94","#f7b6d2","#c7c7c7","#dbdb8d","#9edae5",
]
MARKERS = ["o","s","^","D","v","P","X","*","p","h",
           "<",">","8","H","+","x","d","|","_","1"]


# ══════════════════════════════════════════════════════════════════════════════
#  Header parser
# ══════════════════════════════════════════════════════════════════════════════

def parse_avtime_file(fpath: Path) -> tuple[np.ndarray, dict[str, int]]:
    """
    Read a LAMMPS ave/time output file.
    Returns (data_array, col_index_dict).
    Line 1: "# Timestep ..."  or similar comment
    Line 2: column names
    Remaining lines: data rows.
    """
    with open(fpath) as fh:
        lines = fh.readlines()

    # Find header line (starts with "# " and contains "TimeStep" or "v_")
    header_line = None
    header_lineno = 0
    for i, line in enumerate(lines):
        stripped = line.lstrip("#").strip()
        if "TimeStep" in stripped or "v_alphaWW" in stripped or "c_T_c" in stripped:
            header_line = stripped
            header_lineno = i
            break

    if header_line is None:
        raise ValueError(f"Cannot find column header in {fpath}")

    col_names = header_line.split()
    col_idx = {name: j for j, name in enumerate(col_names)}

    # Parse data rows
    rows = []
    for line in lines[header_lineno + 1:]:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        try:
            rows.append([float(x) for x in stripped.split()])
        except ValueError:
            break

    if not rows:
        raise ValueError(f"No data rows in {fpath}")

    return np.array(rows), col_idx


# ══════════════════════════════════════════════════════════════════════════════
#  Main processing
# ══════════════════════════════════════════════════════════════════════════════

def process(sim_base: Path, res_txt_dir: Path, res_plot_dir: Path,
            comp_label: str = "") -> None:
    """
    Collect SRO parameters from all sim_T directories under sim_base.
    The ave/time output file is named MD_T_<T>K.txt (generated by the pipeline
    LAMMPS input template) or MD_T_<T>K__*.txt (original naming).
    """
    res_txt_dir.mkdir(parents=True, exist_ok=True)
    res_plot_dir.mkdir(parents=True, exist_ok=True)

    sim_dirs = sorted(
        [d for d in sim_base.iterdir()
         if d.is_dir() and d.name.startswith("sim_")],
        key=lambda d: int(d.name.split("_")[1]),
    )

    T_actual_list: list[float] = []
    sro_data: dict[str, list[float]] = {}   # key: "alphaWW", "alphaWMo", …

    for sd in sim_dirs:
        # Find the ave/time output file
        candidates = (
            list(sd.glob("MD_T_*.txt")) +
            list(sd.glob("MD_T_*K.txt"))
        )
        if not candidates:
            print(f"  [skip] no MD_T_*.txt in {sd}")
            continue

        fpath = candidates[-1]   # take last if multiple
        try:
            data, col_idx = parse_avtime_file(fpath)
        except Exception as exc:
            print(f"  [WARN] {fpath}: {exc}")
            continue

        # Use the last row (equilibrated end of run)
        row = data[-1]

        # Extract temperature
        if "c_T_c" in col_idx:
            T_val = row[col_idx["c_T_c"]]
        elif "TimeStep" in col_idx:
            T_nom = int(sd.name.split("_")[1])
            T_val = float(T_nom)
        else:
            T_val = float(sd.name.split("_")[1])

        T_actual_list.append(T_val)

        # Extract all available alpha_ij columns
        for (a, b) in ALL_PAIRS:
            col_name_variants = [
                f"v_alpha{a}{b}",   # pipeline naming
                f"alpha{a}{b}",     # alternative
            ]
            val = None
            for cn in col_name_variants:
                if cn in col_idx:
                    val = float(row[col_idx[cn]])
                    break
            if val is not None:
                key = f"alpha{a}{b}"
                if key not in sro_data:
                    sro_data[key] = []
                sro_data[key].append(val)

    if not T_actual_list:
        print("[sro] No data collected")
        return

    T_arr = np.array(T_actual_list)
    # Only keep pairs where we collected a full set
    n = len(T_arr)
    active_pairs = [k for k, v in sro_data.items() if len(v) == n]

    # ── save CSV ──────────────────────────────────────────────────────────────
    header = "T_actual " + " ".join(active_pairs)
    table = np.column_stack([T_arr] + [sro_data[k] for k in active_pairs])
    csv_path = res_txt_dir / "sro_vs_temp.csv"
    np.savetxt(csv_path, table, header=header, fmt="%.6f", comments="# ")
    print(f"[sro] Saved {csv_path}  ({len(active_pairs)} pairs)")

    # ── plot ──────────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 6))
    for i, key in enumerate(active_pairs):
        color  = COLORS_CYCLE[i % len(COLORS_CYCLE)]
        marker = MARKERS[i % len(MARKERS)]
        # human-readable label: alphaWMo → W-Mo
        a, b = key[5:6], key[6:]
        label = f"{a}-{b}"
        ax.plot(T_arr, sro_data[key], marker=marker, color=color,
                label=label, lw=1.5, ms=5, alpha=0.85)

    ax.axhline(0, color="black", lw=1, ls="--", alpha=0.6)
    ax.set_xlabel("Temperature (K)", fontsize=13)
    ax.set_ylabel(r"Warren-Cowley SRO  $\alpha_{ij}$", fontsize=13)
    ax.set_title(f"SRO vs Temperature  {comp_label}", fontsize=14)
    ax.legend(frameon=True, fontsize=8,
              bbox_to_anchor=(1.02, 1), loc="upper left",
              borderaxespad=0, ncol=2)
    ax.grid(True, which="both", ls=":", alpha=0.5)
    ax.margins(x=0.03, y=0.05)
    fig.tight_layout()
    png_path = res_plot_dir / "sro_vs_temp.png"
    fig.savefig(png_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"[sro] Saved {png_path}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="SRO vs temperature")
    ap.add_argument("--sim_base",  default="../sim_x")
    ap.add_argument("--res_txt",   default="../results/txt")
    ap.add_argument("--res_plot",  default="../results/plots")
    ap.add_argument("--label",     default="")
    args = ap.parse_args()
    process(
        Path(args.sim_base),
        Path(args.res_txt),
        Path(args.res_plot),
        args.label,
    )

